from typing import Protocol, Optional, Any, List

class SettingsRepository(Protocol):
    def get(self, key: str) -> Optional[str]: ...
    def set(self, key: str, value: str) -> None: ...
    def get_bulk(self, prefix: str) -> dict[str, str]: ...
    def delete(self, key: str) -> None: ...
    def delete_bulk(self, prefix: str) -> None: ...
    def exists(self, key: str) -> bool: ...

class AccountRepository(Protocol):
    def create(self, account_data: dict) -> Any: ...
    def get(self, account_id: int) -> Optional[Any]: ...
    def get_tree(self) -> List[Any]: ...
    def update(self, account_id: int, updates: dict) -> Any: ...
    def has_transactions(self, account_id: int) -> bool: ...
    def get_children(self, account_id: int) -> List[Any]: ...

class InstitutionRepository(Protocol):
    def create(self, institution_data: dict) -> Any: ...
    def get(self, institution_id: int) -> Optional[Any]: ...
    def list(self) -> List[Any]: ...
    def update(self, institution_id: int, updates: dict) -> Any: ...

class AccountDetailRepository(Protocol):
    def create_detail(self, detail_type: str, data: dict) -> Any: ...

class TransactionRepository(Protocol):
    def create_transaction(self, tx_data: dict, lines_data: List[dict]) -> Any: ...
    def get_opening_balance_for_account(self, account_id: int) -> Optional[Any]: ...
    def void_transaction(self, tx_id: int) -> None: ...

class SnapshotRepository(Protocol):
    def save_net_worth(self, data: dict) -> Any: ...

class ProfileRepository(Protocol):
    def create(self, profile_data: dict) -> Any: ...
    def get(self, profile_id: int) -> Optional[Any]: ...
    def get_by_name(self, name: str) -> Optional[Any]: ...
    def list(self, limit: int = 10, offset: int = 0, sort_by: str = "id", sort_desc: bool = False, filters: dict = None) -> List[Any]: ...
    def update(self, profile_id: int, updates: dict) -> Optional[Any]: ...
    def delete(self, profile_id: int) -> bool: ...
    def count(self, filters: dict = None) -> int: ...

class GoalRepository(Protocol):
    def create(self, goal_data: dict) -> Any: ...
    def get(self, goal_id: int) -> Optional[Any]: ...
    def update(self, goal_id: int, updates: dict) -> Optional[Any]: ...
    def list(self) -> List[Any]: ...
    def delete_all(self) -> None: ...
