import React, { useState } from 'react';
import { FadeIn, Button, Input } from './components';

export const BGHubScreen = ({ onAuto, onScratch, data }) => (
  <div className="max-w-xl mx-auto py-12 px-6">
    <FadeIn>
      <h2 className="text-4xl font-extrabold text-slate-900 mb-3">Let's give your money a plan.</h2>
      <p className="text-lg text-slate-500 mb-8">A budget isn't about restriction — it's about making sure your money goes where you actually want it to.</p>
      <div className="bg-slate-50 border border-slate-200 p-5 rounded-xl mb-10">
         <strong className="text-slate-800 text-sm">Why we ask:</strong>
         <p className="text-slate-500 text-sm mt-1">Budgeting connects your cash flow to your goals. It shows whether your current spending supports the future you want.</p>
      </div>
      
      <div className="flex flex-col gap-4">
         <Button onClick={onAuto} className="w-full">Auto-generate from my cash flow (1 min)</Button>
         <Button onClick={onScratch} variant="secondary" className="w-full">Build from scratch (3-5 mins)</Button>
      </div>
    </FadeIn>
  </div>
);

export const BGMasterScreen = ({ data, updateData, onComplete }) => {
  const totalIncome = parseFloat(data.cashflow?.income || 0);
  const totalExpenses = Object.values(data.cashflow?.expenses || {}).reduce((acc, v) => acc + (parseFloat(v)||0), 0);
  const surplus = totalIncome - totalExpenses;

  const [alloc, setAlloc] = useState({
    essentials: Math.round(totalExpenses * 0.7),
    lifestyle: Math.round(totalExpenses * 0.3),
    savings: surplus > 0 ? surplus : 0,
    buffer: 0
  });

  const handleUpdate = (cat, val) => {
    setAlloc({...alloc, [cat]: parseInt(val) || 0});
  }

  const handleSave = () => {
    updateData({ budget: { autoGenerated: true, limit: totalExpenses, allocation: alloc } });
    onComplete();
  }

  return (
    <div className="max-w-3xl mx-auto py-12 px-6">
      <FadeIn>
        <span className="text-xs font-bold text-indigo-600 uppercase tracking-widest bg-indigo-50 px-3 py-1 rounded-full mb-4 inline-block">Draft 1</span>
        <h2 className="text-3xl font-extrabold text-slate-900 mb-2">Here's a starting budget.</h2>
        <p className="text-slate-500 mb-8 font-medium">Think of this as a first draft. Adjust anything that doesn't feel right.</p>

        <div className="flex gap-8 mb-10">
          <div className="flex-1 space-y-6">
            <div>
              <label className="text-sm font-bold text-slate-700">Essentials (50-60%)</label>
              <div className="flex items-center gap-3">
                 <input type="number" value={alloc.essentials} onChange={e => handleUpdate('essentials', e.target.value)} className="w-full mt-2 border border-slate-200 rounded-lg p-3 text-slate-800 focus:ring-2 focus:ring-indigo-500 outline-none shadow-sm" />
              </div>
              <p className="text-xs text-slate-500 mt-1.5">Housing, transport, groceries, bills</p>
            </div>
            <div>
              <label className="text-sm font-bold text-slate-700">Lifestyle (20-30%)</label>
              <div className="flex items-center gap-3">
                 <input type="number" value={alloc.lifestyle} onChange={e => handleUpdate('lifestyle', e.target.value)} className="w-full mt-2 border border-slate-200 rounded-lg p-3 text-slate-800 focus:ring-2 focus:ring-indigo-500 outline-none shadow-sm" />
              </div>
              <p className="text-xs text-slate-500 mt-1.5">Dining out, entertainment, shopping</p>
            </div>
            <div>
              <label className="text-sm font-bold text-slate-700">Savings & Goals (20%+)</label>
              <div className="flex items-center gap-3">
                 <input type="number" value={alloc.savings} onChange={e => handleUpdate('savings', e.target.value)} className="w-full mt-2 border border-slate-200 rounded-lg p-3 text-emerald-700 font-bold focus:ring-2 focus:ring-emerald-500 outline-none shadow-sm" />
              </div>
              <p className="text-xs text-emerald-600 mt-1.5">Feeds directly into your goals</p>
            </div>
          </div>
          
          <div className="w-64 bg-slate-50 p-6 rounded-2xl border border-slate-200 shadow-sm flex flex-col justify-center">
            <h3 className="font-bold text-slate-800 tracking-wider text-xs uppercase mb-6 text-center">Your Monthly Pie</h3>
            <div className="space-y-4">
              <div className="flex justify-between items-center text-sm"><span className="text-slate-500 font-medium tracking-tight">Income</span><span className="font-bold text-slate-800">₹{totalIncome}</span></div>
              <div className="flex justify-between items-center text-sm"><span className="text-slate-500 font-medium tracking-tight">Budgeted</span><span className="font-bold text-slate-800">₹{alloc.essentials + alloc.lifestyle + alloc.savings}</span></div>
            </div>
            <div className={`mt-8 pt-6 border-t font-bold flex justify-between tracking-tight ${totalIncome - (alloc.essentials + alloc.lifestyle + alloc.savings) < 0 ? 'text-rose-600 border-rose-100' : 'text-emerald-600 border-emerald-100'}`}>
               <span className="opacity-80">Remaining</span>
               <span className="text-xl">₹{totalIncome - (alloc.essentials + alloc.lifestyle + alloc.savings)}</span>
            </div>
          </div>
        </div>

        <div className="flex justify-end gap-3"><Button onClick={handleSave} className="w-fit px-8">Looks good - save this budget</Button></div>
      </FadeIn>
    </div>
  )
}
