"""CAS (Consolidated Account Statement) parser — supports CAMS and KFintech.

CAS PDFs are generated by CAMS and KFintech for mutual fund portfolios.
They contain investor details, folio blocks, scheme blocks with transaction tables.

Format:
    ─── Investor Header ───────────────────────────────────────────
    Name / PAN / Period

    ─── Folio Block ───────────────────────────────────────────────
    Folio No: 12345678 / SomeFund AMC

        ─── Scheme Block ──────────────────────────────────────────
        Scheme: HDFC Top 100 Fund - Direct Growth (ISIN: INF179KB01BD)
        Opening Balance: 100.000 Units @ ₹250.00 = ₹25,000.00

        Date       | Transaction    | Amount (₹) | Units  | Price  | Unit Balance
        01/01/2026 | Purchase-SIP   | 5,000.00   | 18.345 | 272.54 | 118.345
        15/01/2026 | Redemption     | 10,000.00  | 35.200 | 284.09 | 83.145

Design:
    `parse_text_content()` is the pure, unit-testable entry point.
    ExtractionMethod.TEXT_LAYER is the only method used (CAS PDFs are always digital).
"""

from __future__ import annotations

import logging
import re
from decimal import Decimal, InvalidOperation

from core.models.enums import ExtractionMethod, SourceType, TxnTypeHint
from core.models.raw_parsed_row import ParseMetadata, RawParsedRow
from core.utils.confidence import ConfidenceSignals, compute_confidence
from modules.parser.base import BaseParser, ExtractionResult
from modules.parser.extraction.text_layer import TextLayerExtractor

logger = logging.getLogger(__name__)

# ── CAS-specific patterns ─────────────────────────────────────────────────────

_DATE_RE = re.compile(r"\b(\d{2}-\w{3}-\d{4}|\d{2}/\d{2}/\d{4})\b")

# ── CDSL Demat CAS patterns ───────────────────────────────────────────────────
# CDSL issues a joint CAS covering demat accounts (CDSL/NSDL) and MF folios.
# The transaction and holding rows use a completely different column layout.

# Detect CDSL demat CAS header
_CDSL_DEMAT_HEADER_RE = re.compile(
    r"CONSOLIDATED ACCOUNT STATEMENT.*?DEMAT",
    re.I | re.DOTALL,
)

# CDSL demat transaction row per ISIN (within the "Statement of Transactions" section).
# Example line:
#   INF226401018 LTD#CAPITALMIND MF- 11 03022026C005 03-02-2026 23812.503 597.205 -- 24409.708 0
# Columns: ISIN  SecName  Count  RefCode  Date  OpenBal  Credit  Debit  Closing  StampDuty
_CDSL_TXN_ROW_RE = re.compile(
    r"^(IN[A-Z][A-Z0-9]{9})"       # 12-char ISIN at line start
    r"[^\n]+?"                       # partial security name (non-greedy, no newline)
    r"(\d{2}-\d{2}-\d{4})"          # transaction date DD-MM-YYYY
    r"\s+([\d,]+\.\d{3})"           # opening unit balance
    r"\s+([\d,]+\.\d{3}|--)"        # credit units (-- when none)
    r"\s+([\d,]+\.\d{3}|--)"        # debit units (-- when none)
    r"\s+([\d,]+\.\d{3})",          # closing unit balance
    re.MULTILINE,
)

# CDSL demat holding row per ISIN (within the "Holding Statement" section).
# Example line:
#   INF226401018 LTD#CAPITALMIND MF- 24409.708 -- -- -- 24409.708 10.327 2,52,079.05
#   INE731H01025 EQUIPMENTS LIMITED - EQUITY 200.000 -- -- -- 200.000 884.900 1,76,980.00
# Columns: ISIN  SecName  CurrBal  Frozen  Pledge  SetupFree  FreeBal  Price/NAV  Value
_CDSL_HOLDING_ROW_RE = re.compile(
    r"^(IN[A-Z][A-Z0-9]{9})"       # 12-char ISIN at line start
    r"[^\n]+?"                       # partial security name (non-greedy, no newline)
    r"([\d,]+\.\d{3})"              # current balance
    r"\s+--\s+--\s+--"              # frozen/pledge/setup-free all zero (--)
    r"\s+([\d,]+\.\d{3})"           # free balance (= current for fully active holding)
    r"\s+([\d,]+\.\d{3,4})"         # face value / NAV / market price per unit
    r"\s+([\d,]+\.\d{2})",          # total market value
    re.MULTILINE,
)
_ISIN_RE = re.compile(r"\bISIN\s*[:\-]\s*([A-Z]{2}[A-Z0-9]{10})\b")
_FOLIO_RE = re.compile(r"Folio\s+No\s*[:\-]\s*([\w\d]+)", re.I)
_SCHEME_RE = re.compile(r"^(.*?(?:Fund|ETF|Plan|Scheme).*?)\s*(?:\(ISIN|ISIN)")

# Transaction row: Date | TxnType | Amount | Units | Price | Unit Balance
# CAS uses a pipe-or-whitespace delimited format
_TXN_ROW_RE = re.compile(
    r"""
    ^(\d{2}[-/]\w{2,3}[-/]\d{4})   # Date
    \s+
    ([\w\s\-]+?)                     # Transaction type (non-greedy)
    \s+
    ([\d,]+\.\d{2,3})               # Amount
    \s+
    ([\d]+\.[\d]{3})                 # Units
    \s+
    ([\d,]+\.\d{4})                  # Nav / Price per unit
    \s+
    ([\d]+\.[\d]{3})                 # Closing unit balance
    """,
    re.VERBOSE | re.MULTILINE,
)

# CAS transaction type text → TxnTypeHint
_CAS_TXN_TYPE_MAP: list[tuple[re.Pattern[str], TxnTypeHint]] = [
    (re.compile(r"Purchase|SIP|NFO|Switch.In|STP.In", re.I), TxnTypeHint.PURCHASE),
    (re.compile(r"Redemption|Switch.Out|STP.Out", re.I), TxnTypeHint.REDEMPTION),
    (re.compile(r"Dividend\s+Payout", re.I), TxnTypeHint.DIVIDEND_PAYOUT),
    (re.compile(r"Dividend\s+Reinvest", re.I), TxnTypeHint.DIVIDEND_REINVEST),
    (re.compile(r"Bonus", re.I), TxnTypeHint.BONUS),
    (re.compile(r"\bSIP\b", re.I), TxnTypeHint.SIP),
]


def _map_cas_txn_type(raw_type: str) -> TxnTypeHint:
    for pattern, hint in _CAS_TXN_TYPE_MAP:
        if pattern.search(raw_type):
            return hint
    return TxnTypeHint.UNKNOWN


class CasParser(BaseParser):
    """Parses CAMS and KFintech CAS (Consolidated Account Statement) PDFs.

    Both CAMS and KFintech produce similar formats, so this single parser
    handles both SourceType.CAS_CAMS and SourceType.CAS_KFINTECH.
    """

    source_type = SourceType.CAS_CAMS      # Registry also maps CAS_KFINTECH here
    version = "1.0"
    supported_formats = ["PDF"]

    def __init__(self) -> None:
        self._text_extractor = TextLayerExtractor()

    def supported_methods(self) -> list[ExtractionMethod]:
        # CAS PDFs are always digitally generated — text layer only
        return [ExtractionMethod.TEXT_LAYER]

    def extract(
        self,
        batch_id: str,
        file_bytes: bytes,
        method: ExtractionMethod,
    ) -> ExtractionResult:
        try:
            pages = self._text_extractor.extract_pages(file_bytes)
            combined = "\n".join(pages)
            if not combined.strip():
                return self._make_failed_result(batch_id, method, "No text in CAS PDF.")
            return self.parse_text_content(batch_id, combined, method)
        except Exception as exc:  # noqa: BLE001
            logger.warning("CasParser.extract failed: %s", exc, exc_info=True)
            return self._make_failed_result(batch_id, method, str(exc))

    # ── Core parsing logic (pure — unit-testable) ─────────────────────────────

    def parse_text_content(
        self,
        batch_id: str,
        text: str,
        method: ExtractionMethod = ExtractionMethod.TEXT_LAYER,
    ) -> ExtractionResult:
        """Parse CAS statement text into RawParsedRow objects.

        Dispatches to CDSL-demat handler when the document is a joint CDSL/MF CAS,
        otherwise falls through to the traditional MF CAS folio/scheme parser.
        """
        if _CDSL_DEMAT_HEADER_RE.search(text):
            return self._parse_cdsl_demat_cas(batch_id, text, method)

        return self._parse_mf_cas(batch_id, text, method)

    def _parse_cdsl_demat_cas(
        self,
        batch_id: str,
        text: str,
        method: ExtractionMethod,
    ) -> ExtractionResult:
        """Parse CDSL joint CAS (demat securities + MF units held in demat form).

        Extracts unit movements from the 'Statement of Transactions' section and
        cross-references with the 'Holding Statement' section for NAV/price.
        Transaction amounts are estimated as units × current NAV (end-of-period).
        """
        rows: list[RawParsedRow] = []
        errors: list[str] = []

        # Build NAV / price lookup from holding rows  {ISIN: (nav_str, value_str)}
        nav_lookup: dict[str, tuple[str, str]] = {}
        for m in _CDSL_HOLDING_ROW_RE.finditer(text):
            isin = m.group(1)
            nav_lookup[isin] = (
                m.group(4).replace(",", ""),
                m.group(5).replace(",", ""),
            )

        # Capture account hint from first DP/Client ID pair in text
        account_hint: str | None = None
        dp_match = re.search(r"DP\s+Id\s*:\s*(\d+)\s+Client\s+Id\s*:\s*(\d+)", text, re.I)
        if dp_match:
            account_hint = f"CDSL/{dp_match.group(1)}/{dp_match.group(2)}"

        for m in _CDSL_TXN_ROW_RE.finditer(text):
            isin = m.group(1)
            raw_date = m.group(2)          # DD-MM-YYYY
            credit_units = m.group(4)
            debit_units = m.group(5)
            closing_units = m.group(6)

            is_credit = credit_units != "--"
            is_debit = debit_units != "--"
            if not is_credit and not is_debit:
                continue

            units_str = credit_units if is_credit else debit_units
            nav_str, _ = nav_lookup.get(isin, (None, None))

            # Estimate amount = units × current NAV (end-of-period approximation)
            raw_amount: str | None = None
            if nav_str:
                try:
                    raw_amount = str(round(
                        Decimal(units_str.replace(",", "")) * Decimal(nav_str), 2
                    ))
                except InvalidOperation:
                    errors.append(f"Amount calculation failed for ISIN {isin}")

            txn_type = TxnTypeHint.PURCHASE if is_credit else TxnTypeHint.REDEMPTION

            rows.append(
                RawParsedRow(
                    batch_id=batch_id,
                    source_type=self.source_type,
                    parser_version=self.version,
                    extraction_method=method,
                    raw_date=raw_date,
                    raw_narration=f"{'SIP/Purchase' if is_credit else 'Redemption'} - {isin}",
                    raw_debit=raw_amount if is_credit else None,
                    raw_credit=raw_amount if is_debit else None,
                    raw_quantity=units_str,
                    raw_unit_price=nav_str,
                    raw_balance=closing_units,
                    txn_type_hint=txn_type,
                    folio_id=account_hint,
                    fund_isin=isin,
                    row_confidence=0.75 if raw_amount else 0.55,
                    row_number=len(rows) + 1,
                    extra_fields={
                        "opening_units": m.group(3),
                        "is_amount_estimated": True,
                    },
                )
            )

        if not rows:
            errors.append(
                "No transactions found in CDSL CAS — document may be a holdings-only statement."
            )

        warnings = list(errors)
        if rows:
            warnings.append(
                "Amounts are estimated (units × end-of-period NAV). "
                "Verify against contract notes for exact purchase price."
            )

        signals = ConfidenceSignals(
            balance_cross_check_passed=None,
            all_rows_have_valid_date=bool(rows) and all(r.raw_date for r in rows),
            all_rows_have_amount=bool(rows) and all(r.raw_debit or r.raw_credit for r in rows),
            row_count_positive=len(rows) > 0,
            no_row_parse_errors=len(errors) == 0,
        )
        confidence = compute_confidence(signals)
        dates = [r.raw_date for r in rows if r.raw_date]
        meta = ParseMetadata(
            statement_from=dates[0] if dates else None,
            statement_to=dates[-1] if dates else None,
            account_hint=account_hint,
            total_rows_found=len(rows),
            rows_with_errors=len(errors),
            overall_confidence=confidence,
            warnings=warnings,
            extraction_method=method,
            parser_version=self.version,
        )
        return ExtractionResult(rows=rows, metadata=meta, method=method, confidence=confidence)

    def _parse_mf_cas(
        self,
        batch_id: str,
        text: str,
        method: ExtractionMethod,
    ) -> ExtractionResult:
        """Parse traditional CAMS/KFintech mutual-fund CAS (folio → scheme → transactions)."""
        rows: list[RawParsedRow] = []
        errors: list[str] = []
        current_folio: str | None = None
        current_isin: str | None = None
        current_scheme: str | None = None

        for line_num, line in enumerate(text.splitlines(), start=1):
            line = line.strip()
            if not line:
                continue

            # Track folio context
            folio_match = _FOLIO_RE.search(line)
            if folio_match:
                current_folio = folio_match.group(1)
                continue

            # Track ISIN + scheme context
            isin_match = _ISIN_RE.search(line)
            if isin_match:
                current_isin = isin_match.group(1)
                scheme_match = _SCHEME_RE.match(line)
                if scheme_match:
                    current_scheme = scheme_match.group(1).strip()
                continue

            # Parse transaction row
            txn_match = _TXN_ROW_RE.match(line)
            if txn_match:
                raw_date = txn_match.group(1)
                raw_txn_type = txn_match.group(2).strip()
                raw_amount = txn_match.group(3)
                raw_units = txn_match.group(4)
                raw_price = txn_match.group(5)
                raw_unit_balance = txn_match.group(6)

                txn_type = _map_cas_txn_type(raw_txn_type)
                is_purchase = txn_type in (
                    TxnTypeHint.PURCHASE,
                    TxnTypeHint.SIP,
                    TxnTypeHint.STP_IN,
                    TxnTypeHint.SWITCH_IN,
                )

                rows.append(
                    RawParsedRow(
                        batch_id=batch_id,
                        source_type=self.source_type,
                        parser_version=self.version,
                        extraction_method=method,
                        raw_date=raw_date,
                        raw_narration=raw_txn_type,
                        raw_debit=raw_amount if is_purchase else None,
                        raw_credit=raw_amount if not is_purchase else None,
                        raw_quantity=raw_units,
                        raw_unit_price=raw_price,
                        raw_balance=raw_unit_balance,
                        txn_type_hint=txn_type,
                        folio_id=current_folio,
                        fund_isin=current_isin,
                        row_confidence=0.9,
                        row_number=len(rows) + 1,
                        extra_fields={"scheme_name": current_scheme} if current_scheme else {},
                    )
                )

        signals = ConfidenceSignals(
            balance_cross_check_passed=False,  # Unit balance check done in SM-E
            all_rows_have_valid_date=bool(rows) and all(bool(r.raw_date.strip()) for r in rows),
            all_rows_have_amount=bool(rows) and all(r.raw_debit or r.raw_credit for r in rows),
            row_count_positive=len(rows) > 0,
            no_row_parse_errors=len(errors) == 0,
        )
        confidence = compute_confidence(signals)
        dates = [r.raw_date for r in rows if r.raw_date]
        meta = ParseMetadata(
            statement_from=dates[0] if dates else None,
            statement_to=dates[-1] if dates else None,
            total_rows_found=len(rows),
            rows_with_errors=len(errors),
            overall_confidence=confidence,
            warnings=errors,
            extraction_method=method,
            parser_version=self.version,
        )
        return ExtractionResult(rows=rows, metadata=meta, method=method, confidence=confidence)


# ── KFintech variant ──────────────────────────────────────────────────────────

# KFintech CAS PDFs use "Folio:" instead of "Folio No:"
_KFINTECH_FOLIO_RE = re.compile(r"\bFolio\s*:", re.I)


class CasKfintechParser(CasParser):
    """CAS parser variant for KFintech format.

    KFintech CAS PDFs differ from CAMS in one key aspect:
    - Folio header is "Folio: <number>" instead of "Folio No: <number>"

    This subclass normalises the text before delegating to CasParser, then
    stamps the correct SourceType on every returned row.
    """

    source_type = SourceType.CAS_KFINTECH
    version = "1.0"

    def parse_text_content(
        self,
        batch_id: str,
        text: str,
        method: ExtractionMethod = ExtractionMethod.TEXT_LAYER,
    ) -> ExtractionResult:
        # Normalise KFintech folio header to match CasParser's _FOLIO_RE pattern
        normalised = _KFINTECH_FOLIO_RE.sub("Folio No:", text)
        result = super().parse_text_content(batch_id, normalised, method)
        # Stamp every row with the correct source type
        for row in result.rows:
            row.source_type = SourceType.CAS_KFINTECH
        return result
